[phases.setup]
nixPkgs = [
    "gcc",
    "python311",
    "ffmpeg",
    "tesseract",
    "stdenv.cc.cc.lib"
]

[phases.build]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn run:app --bind=0.0.0.0:$PORT"